version: '3'
services:

  db:
    env_file: common.env
    container_name: ${DB_HOST}
    hostname: ${DB_HOST}
    user: "${UID}:${GID}"
    networks:
      - spike
    image: postgres:13.2
    volumes:
      - ../db:/var/lib/postgresql/data
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - "5432:5432"

  webapp:
    image: ${COMPOSE_PROJECT_NAME}-webapp
    container_name: ${COMPOSE_PROJECT_NAME}-webapp
    hostname: ${COMPOSE_PROJECT_NAME}-webapp
    env_file: common.env
    restart: "${RESTART_POLICY:-no}"
    environment:
      - APP_UID=${UID}
    networks:
      - spike
    depends_on:
      - db      
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../node_modules:/app/node_modules
    ports:
      - "3000:3000"

networks:
  spike:
    driver: bridge
